Repository DP2-C1-021/Acme-ANS-C2, pull requests merged in 2025-02, with the labels that each got.

#28 Add reports D01
  reports/Group/D01/Testing Report- D01.docx
  reports/Student #2/02 - Requirements - Student #2.docx
  reports/Student #2/D01/Analysis Report - D01 -Student#2 - virmesper.docx
  reports/Student #2/D01/DUMMY.txt
  reports/Student #2/D01/PlanningAndProgress Report - D01 -Student 2- virmesper.docx
Labels: documentation

#46 Add UML
  CHANGELOG.txt
  reports/Student #2/D02/suplementario1.drawio.png
Labels: documentation

#55 Update Entities
  src/main/java/acme/entities/S2/Booking.java
  src/main/java/acme/entities/S2/Customer.java
  src/main/java/acme/entities/S2/Passenger.java
  src/main/java/acme/realms/Customer.java
Labels: bug

#78 feat: add service entity
  src/main/java/acme/entities/Group/Service.java
  src/main/java/acme/entities/S5/MaintenanceRecord.java
  src/main/java/acme/entities/S5/Task.java
  src/main/java/acme/entities/S5/Technician.java
Labels: feature
